### ISSUE TITLE
Love this - wasn't able to get it to work though

### ISSUE THREAD

**Issue by alonbardavid** [cellog/react-redux-saga-router#9]
Just wanted to say - thank you for making this. 
I really don't like all the solutions available now for redux routing and this is more or less what I thought about making on my own. I'm glad someone else is making it :)

Obviously it's in a very early state, but as far as I can tell, it doesn't work with what the guidelines in the README provide.

As far as I can tell, the issue I ran into is that `listenForRoutes` is never registered, which means that CREATE_ROUTE doesn't really add a route.
At this point I gave up (it's probably surmountable but too much fiddling doesn't really fit into what I'm doing at this time).

If you want any help, let me know.

A few things to note:
1. I couldn't get it to work with create-react-app off the bat, I needed to add `require('babel-polyfill')` at the top entry point - though other libraries with generators work. Might want to think about building the lib with inlined "regenerator runtime", though I don't remember how to do that.
2. If all works as intended, you'll get CREATE_ROUTE and ADD_ROUTE actions in the redux history for every route that exists. This really pollutes the history and will cause a lot of re-rendering, might want to think of a different solution - all of it should probably be in the initial state of the reducer somehow.

**Comment by cellog** [comment]
Thanks for the feedback. I am traveling today, but will relish digging in to see what I can do to fix this issue. 

I have been using the 3rd option to the router setup, where routes can be passed in statically rather than as a component, but I will definitely create an app that uses the documented way now that I know these issues exist (and are outside the scope of the current tests, so those need to be updated as well to reflect these issues) 

I also have not tried it with an es5 app, so that is important to note the dependency on generator runtime, I will read up and either include an implementation or document how to include it. 

Thanks for the feedback!

**Comment by cellog** [comment]
So a quick look at the code shows me a couple of simple bugs, and one more subtle but big one. 

First, this line is all that is needed to enable the Route tag:

```javascript
yield fork(listenForRoutes) 
```

At the start of `router`

Within `listenForRoutes`, I need to `fork() ` rather than `call()`

The more subtle bug is there is no checking whether the route has been registered or not. We need to check this in order to cancel the running sagas, and so I will add that functionality. 

As for re-rendering, I can look into batching them inside the parent `Routes` component and dispatching one action to register them all. Shouldn't be too tough.

**Comment by cellog** [comment]
OK, update on the batched route creation.  After some investigation, I think the best approach is to recommend that for performance-intensive apps, an optimization is to move the routes to the router() call.  For dynamically loaded routes, the extra renders won't be a huge performance penalty.  If I hear of a use case that makes this performance an issue, I'll add a new way of making routes that is batched.

**Comment by cellog** [comment]
second update: I figured out a way to do batched route creation with a single action.  It only works on the client-side.  On the server, the only way to do a batched create is by passing the routes to the router initialization function.  This is not currently documented, but I'll do that soon.

**Comment by cellog** [comment]
latest commit implements batched create and a whole host of improvements.  There is one BATCH_ROUTES action for every <Router> tag.  On the server, routes are dispatched with EDIT_ROUTE actions, as there is no way to batch them.
